[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
OhMyCards = "1d55750c-489b-49e7-adc5-a004f92ae42b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TemplateDocsVitePress = "6096575d-799d-4116-8a3c-c22801a427cb"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
